language: objective-c
osx_image: xcode7.2
install:
- gem install xcpretty --no-rdoc --no-ri --no-document
- gem install cocoapods --no-rdoc --no-ri --no-document
- gem install jazzy --no-rdoc --no-ri --no-document
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
script:
- open -b com.apple.iphonesimulator
- set -o pipefail && xcodebuild test -scheme 'Deferred' -sdk macosx | xcpretty -c
- set -o pipefail && xcodebuild test -scheme 'MobileDeferred' -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 5' | xcpretty -c
- set -o pipefail && xcodebuild test -scheme 'TVDeferred' -sdk appletvsimulator -destination
  'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -c
- carthage build --no-skip-current
- pod lib lint --quick
after_success:
- "./Configurations/publish_docs.sh"
notifications:
  slack:
    secure: B1vBvRCVa/IJZKtuRGLastyhSZQwP5coR3+/JOrBMXWE+5733MI0u6i462FVKfNfpPkSGS7t1/PXBknX/dF5auzAGsUyKZOuvyUfPe/Sd+kMOaIPw7M8fGONml0jQT0H/OgayZY3wcrlNm42yYFwzQdGd3HBfZIDkM2Ui5P/kn8=
