matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.4
      install: bundle install --quiet
      script: bundle exec fastlane mac ci
    - language: objective-c
      os: osx
      osx_image: xcode10.1
      install: bundle install --quiet
      script: bundle exec fastlane ios ci
      after_failure:
        - cat ~/Library/Developer/Xcode/DerivedData/Deferred-*/Logs/Test/*/Session-MobileDeferredTests-*.log | true
        - cat ~/Library/Logs/scan/Deferred-*.log | true
    - language: generic
      os: linux
      dist: trusty
      sudo: required
      env: SWIFT_VERSION=4.1
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift test --parallel
    - language: generic
      os: linux
      dist: trusty
      sudo: required
      env: SWIFT_VERSION=4.2.1
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script:
        - swift --version
        - swift test --parallel
notifications:
  email: false
