language: objective-c
osx_image: xcode7.2
install:
- gem install scan --no-rdoc --no-ri --no-document
- gem install cocoapods --no-rdoc --no-ri --no-document
- gem install jazzy --no-rdoc --no-ri --no-document
- curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
- sudo installer -pkg "Carthage.pkg" -target /
- rm "Carthage.pkg"
env:
- SCAN_OPEN_REPORT=false
before_script:
- set -o pipefail
script:
- scan -s Deferred
- scan -s MobileDeferred
- scan -s TVDeferred
- carthage build --no-skip-current --configuration Debug
- pod lib lint --quick
after_success:
- "./Configurations/publish_docs.sh"
notifications:
  slack:
    secure: B1vBvRCVa/IJZKtuRGLastyhSZQwP5coR3+/JOrBMXWE+5733MI0u6i462FVKfNfpPkSGS7t1/PXBknX/dF5auzAGsUyKZOuvyUfPe/Sd+kMOaIPw7M8fGONml0jQT0H/OgayZY3wcrlNm42yYFwzQdGd3HBfZIDkM2Ui5P/kn8=
