name: CI
on:
  push:
    branches-ignore:
    - gh-pages
jobs:
  test_iOS:
    name: Test iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Gem Update
      run: gem update
    - name: Run Swift Test
      run: bundle exec fastlane mac test
    # - name: Run xcodebuild
    #   env:
    #     SCHEME: MobileDeferred
    #     DESTINATION: platform=iOS Simulator,name=iPhone 11,OS=latest
    #   run: xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" -quiet test
  test_macOS:
    name: Test macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Gem Update
      run: gem update
    - name: Run swift test
      run: bundle exec fastlane mac test
    # - name: Check build for playgrounds
    #   env:
    #     SCHEME: MobileDeferred
    #     DESTINATION: 'generic/platform=macOS'
    #   run: xcodebuild -scheme "$SCHEME" -destination "$DESTINATION" SWIFT_ACTIVE_COMPILATION_CONDITIONS="XCODE FORCE_PLAYGROUND_COMPATIBILITY" -quiet build
    # - name: Run pod lib lint
    #   run: pod lib lint --use-libraries --skip-tests --platforms=macos
  test_Linux:
    name: Test Linux
    runs-on: ubuntu-latest
    container: swift:5.3
    steps:
    - uses: actions/checkout@v1
    - name: Run swift test
      run: swift test --parallel --sanitize=thread
    - name: Run swiftlint
      uses: norio-nomura/action-swiftlint@3.1.0
